Repository galaxyproject/galaxy-helm, pull requests merged in 2021-03, with the labels that each got.

#231 Adding explicit empty string
  galaxy/values.yaml
Labels: patch

#196 [WIP] Update README for 3.6.0 & 20.09
  README.md
Labels: paper-cut

#221 Better handling for extraFileMappings
  galaxy/templates/_helpers.tpl
  galaxy/templates/configmap-extra-files.yaml
  galaxy/templates/deployment-job.yaml
  galaxy/templates/deployment-web.yaml
  galaxy/templates/deployment-workflow.yaml
Labels: paper-cut, patch

#235 appVersion string
  galaxy/Chart.yaml
Labels: patch

#240 Pull policy on initcontainers
  galaxy/templates/deployment-job.yaml
  galaxy/templates/deployment-web.yaml
  galaxy/templates/deployment-workflow.yaml
Labels: patch

#241 Trimming newline on pod priority class
  galaxy/values.yaml
Labels: patch

#245 Test branch
  galaxy/values.yaml
Labels: feature

#246 Test CI
  galaxy/values.yaml
Labels: feature

#247 Test Ci fork
  galaxy/values.yaml
Labels: feature

#248 Citest
  galaxy/values.yaml
Labels: feature

#249 CI Test
  galaxy/values.yaml
Labels: feature

#236 Separate workflow from job handlers
  .gitignore
  galaxy/templates/deployment-workflow.yaml
  galaxy/values.yaml
Labels: feature

#234 Upgrade templates to match helm 3
  galaxy/Chart.yaml
  galaxy/requirements.lock
  galaxy/requirements.yaml
  galaxy/templates/NOTES.txt
  galaxy/templates/_helpers.tpl
  galaxy/templates/configmap-extra-files.yaml
  galaxy/templates/configmap-galaxy-rules.yaml
  galaxy/templates/configmap-grafana-dashboard.yaml
  galaxy/templates/configmap-nginx.yaml
  galaxy/templates/configs-galaxy.yaml
  galaxy/templates/deployment-job.yaml
  galaxy/templates/deployment-metrics.yaml
  galaxy/templates/deployment-nginx.yaml
  galaxy/templates/deployment-web.yaml
  galaxy/templates/deployment-workflow.yaml
  galaxy/templates/hapostgres/pgcluster.yaml
  galaxy/templates/hapostgres/secret-pgcluster-galaxy-user.yaml
  galaxy/templates/hapostgres/secret-pgcluster-postgres.yaml
  galaxy/templates/ingress-activity-canary.yaml
  galaxy/templates/ingress.yaml
  galaxy/templates/priorityclass-job.yaml
  galaxy/templates/pvc-cvmfs-data.yaml
  galaxy/templates/pvc-cvmfs-main.yaml
  galaxy/templates/pvc-galaxy.yaml
  galaxy/templates/rbac-job.yaml
  galaxy/templates/secret-galaxy.yaml
  galaxy/templates/secret-initdb.yaml
  galaxy/templates/service-nginx.yaml
  galaxy/templates/service-uwsgi.yaml
  galaxy/templates/service.yaml
  galaxy/templates/serviceaccount.yaml
  galaxy/templates/tests/test-connection.yaml
  galaxy/values.yaml
Labels: feature

#251 Removing old scripts
  galaxy/scripts/delete
  galaxy/scripts/install
  galaxy/scripts/test-install
Labels: patch

#255 [RFC] API Versioning
  galaxy/templates/ingress-activity-canary.yaml
  galaxy/templates/ingress.yaml
  galaxy/templates/priorityclass-job.yaml
Labels: help wanted

#173 Lists to keys
  galaxy/files/rules/k8s_container_mapper.py
  galaxy/files/rules/test_k8s_container_mapper.py
  galaxy/values.yaml
Labels: paper-cut
