Repository galaxyproject/galaxy-helm, pull requests merged in 2021-06, with the labels that each got.

#297 Load extraFileMappings using .Files.Get if a path is defined.
  galaxy/templates/configmap-extra-files.yaml
Labels: enhancement, feature

#302 Documentation for extraFileMappings changes
  README.md
Labels: enhancement

#301 logo_src default with path
  galaxy/values.yaml
Labels: patch, values

#300 Trim suffix when installing canary ingress
  galaxy/templates/ingress-activity-canary.yaml
Labels: bug, patch
