Repository galaxyproject/galaxy-helm, pull requests merged in 2022-08, with the labels that each got.

#359 Added support for loading refdata from s3
  .github/workflows/test.yaml
  README.md
  galaxy/Chart.yaml
  galaxy/templates/_helpers.tpl
  galaxy/templates/deployment-job.yaml
  galaxy/templates/deployment-web.yaml
  galaxy/templates/deployment-workflow.yaml
  galaxy/templates/jobs-init.yaml
  galaxy/templates/pv-s3fs.yaml
  galaxy/templates/pvcs-cvmfs.yaml
  galaxy/values.yaml
  scripts/values_table.py
Labels: feature, major

#371 Remove the galaxy-cvmfs-csi dependency.
  galaxy/Chart.yaml
Labels: enhancement

#354 Replace container mapper rules with TPV
  galaxy/files/rules/__init__.py
  galaxy/files/rules/k8s_container_mapper.py
  galaxy/files/rules/test_k8s_container_mapper.py
  galaxy/values.yaml
Labels: enhancement, feature
