Repository galaxyproject/galaxy-helm, pull requests merged in 2024-11, with the labels that each got.

#501 Update dependency charts; save outputs to working dir
  .github/workflows/test.yaml
  .gitignore
  galaxy/Chart.yaml
  galaxy/values.yaml
Labels: minor

#505 Use the newly-supported shorthand tool ids for the sanitize allowlist
  galaxy/values.yaml
Labels: enhancement, minor

#506 Refactor helm chart, splitting operator deps into separate chart
  .github/workflows/test.yaml
  README.md
  VALUES.md
  galaxy/Chart.yaml
  galaxy/disabled/configmap-galaxy.yaml
  galaxy/postgres-pv.yaml
  galaxy/templates/configmap-cvmfs-fix.yaml
  galaxy/templates/hook-cvmfs-fix.yaml
  galaxy/values.yaml
Labels: refactoring
