Repository galaxyproject/galaxy-helm, pull requests merged in 2024-04, with the labels that each got.

#314 Changes for not mounting entire NFS to each job
  galaxy/values.yaml
Labels: enhancement, minor

#458 Add YAML document separators
  galaxy/templates/configmap-cvmfs-fix.yaml
  galaxy/templates/configmap-extra-files.yaml
  galaxy/templates/configmap-galaxy-rules.yaml
  galaxy/templates/configmap-grafana-dashboard.yaml
  galaxy/templates/configmap-nginx.yaml
  galaxy/templates/configs-galaxy.yaml
  galaxy/templates/cronjob-maintenance.yaml
  galaxy/templates/deployment-celery-beat.yaml
  galaxy/templates/deployment-celery.yaml
  galaxy/templates/deployment-job.yaml
  galaxy/templates/deployment-metrics.yaml
  galaxy/templates/deployment-nginx.yaml
  galaxy/templates/deployment-tusd.yaml
  galaxy/templates/deployment-web.yaml
  galaxy/templates/deployment-workflow.yaml
  galaxy/templates/hook-cvmfs-fix.yaml
  galaxy/templates/ingress-activity-canary.yaml
  galaxy/templates/ingress-tusd.yaml
  galaxy/templates/ingress.yaml
  galaxy/templates/jobs-init.yaml
  galaxy/templates/priorityclass-job.yaml
  galaxy/templates/pv-s3fs.yaml
  galaxy/templates/pvc-galaxy.yaml
  galaxy/templates/pvc-refdata.yaml
  galaxy/templates/rabbitmqcluster.yaml
  galaxy/templates/rbac-job.yaml
  galaxy/templates/secret-galaxy.yaml
  galaxy/templates/service-galaxy.yaml
  galaxy/templates/service-nginx.yaml
  galaxy/templates/service-tusd.yaml
  galaxy/templates/serviceaccount.yaml
Labels: bug, paper-cut

#460 Run tests with 1.28, and add missing tool versions to sanitize allowlist
  .github/workflows/test.yaml
  galaxy/values.yaml
Labels: enhancement, minor

#448 Cron job maintenance
  README.md
  galaxy/disabled/configmap-galaxy.yaml
  galaxy/templates/_helpers.tpl
  galaxy/templates/cronjob-maintenance.yaml
  galaxy/templates/hook-cvmfs-fix.yaml
  galaxy/values.yaml
Labels: enhancement, minor

#470 Persist credentials and set GH_TOKEN for the GitHub command line tool
  .github/workflows/packaging.yml
Labels: bug, patch

#469 Document enabled flag for cron jobs
  README.md
Labels: enhancement, minor
