Repository galaxyproject/galaxy-helm, pull requests merged in 2024-08, with the labels that each got.

#491 Update s3-csi version
  galaxy/Chart.yaml
Labels: patch

#497 Set the name of the CVMFS alien cache
  galaxy/values.yaml
Labels: bug

#498 Make CVMFS fix configurable
  README.md
  VALUES.md
  galaxy/templates/configmap-cvmfs-fix.yaml
  galaxy/templates/hook-cvmfs-fix.yaml
  galaxy/values.yaml
Labels: patch, minor
